server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ztg123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncodeing=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:/com/example/demo/mapper/*Mapper.xml
  configuration:
    # 将mybatis日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动驼峰命名自动映射
    map-underscore-to-camel-case: true

logging:
  file:
    name: log/log.log
  level:
    root: info
    demo: debug